import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdcc1",
        "surface-tint": "#006877",
        secondary: "#632ce5",
        "tertiary-container": "#a75d00",
        surface: "#f6fafb",
        "outline-variant": "#bdc8cb",
        "primary-container": "#007b8c",
        "surface-container": "#ebeeef",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#6c3a00",
        background: "#f6fafb",
        "secondary-fixed": "#e8deff",
        "on-tertiary-fixed": "#2e1500",
        "on-secondary-fixed": "#20005f",
        outline: "#6e797c",
        "on-surface": "#181c1d",
        "surface-container-high": "#e5e9ea",
        tertiary: "#844800",
        "secondary-container": "#7c4dff",
        "surface-dim": "#d7dbdc",
        error: "#ba1a1a",
        "on-error-container": "#93000a",
        "surface-container-highest": "#dfe3e4",
        "secondary-fixed-dim": "#cdbdff",
        "surface-variant": "#dfe3e4",
        "on-background": "#181c1d",
        primary: "#00606e",
        "surface-container-low": "#f1f4f5",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb778",
        "primary-fixed": "#a3eeff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#004e5a",
        "on-secondary-container": "#fcf6ff",
        "on-secondary-fixed-variant": "#4f00d0",
        "on-primary-fixed": "#001f25",
        "surface-bright": "#f6fafb",
        "on-tertiary-container": "#fff2ea",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3132",
        "on-primary-container": "#e0f9ff",
        "on-surface-variant": "#3e494b",
        "inverse-on-surface": "#eef1f2",
        "primary-fixed-dim": "#7ad4e6",
        "inverse-primary": "#7ad4e6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
