services:
  frontend:
    container_name: divitup-frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    environment:
      - MINDEE_API_KEY=${MINDEE_API_KEY}
      - MINDEE_MODEL_ID=${MINDEE_MODEL_ID}
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
